### ISSUE TITLE
`.../api.lua:180` attempt to call field `prime` (a nil value)

### ISSUE THREAD

**Issue by chxp82q** [dharmx/nvim-colo#4]
Getting a nil error when updating to the latest commit.

```
Error detected while processing /etc/nixos/config/nvim/init.lua:
E5113: Error while calling lua chunk: ...e/nvim/site/pack/packer/start/nvim-colo/lua/colo/api.lua:180: attempt to call field 'prime' (a nil va
stack traceback:
        ...e/nvim/site/pack/packer/start/nvim-colo/lua/colo/api.lua:180: in function 'override'
        ...e/nvim/site/pack/packer/start/nvim-colo/lua/colo/api.lua:97: in function 'all'
        ...e/nvim/site/pack/packer/start/nvim-colo/lua/colo/api.lua:41: in function 'set'
        .../nvim/site/pack/packer/start/nvim-colo/lua/colo/init.lua:20: in function 'setup'
        /home/javacafe01/.config/nvim/lua/plugins/nvim-colo.lua:115: in main chunk
        [C]: in function 'require'
Sessions list is empty
```

Currently reverted to the last working commit, 6d6c1bf603d63caf39ef148517fd8eb80287c36d

**Comment by dharmx** [comment]
Yes, I am currently refactoring this entire plugin. And, somehow I forgot to create a different branch for it :(. So, a nice way to lock updating this plugin (if you're using packer.nvim) is to add `commit = a401cad1762b458332d563484c05eb149bfa7a48` as mentioned [here](https://github.com/wbthomason/packer.nvim/#specifying-plugins).

**Comment by dharmx** [comment]
I will try to find a way to migrate these into the `dev` branch.

**Comment by dharmx** [comment]
Alright! I have reverted the commits. Let me know if it works.
